### ISSUE TITLE
Implement continuous integration github actions to trigger build upon any release of dragonfly-schema

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/dragonfly-schema-dotnet#2]
This is the repo that needs the "CI-style" script like the one on pollination-apiary. This should receive a payload from the [dragonfly-schema](https://github.com/ladybug-tools/dragonfly-schema) repo, rebuild the C# code from the payload, and trigger a new release.

It should receive the [Model OpenAPI definition](https://github.com/ladybug-tools/dragonfly-schema/blob/gh-pages/model.json) or a link to this JSON and use it to run the [generate.sh](https://github.com/ladybug-tools/dragonfly-schema-dotnet/blob/master/.openapi-generator/generate.sh) script that rebuilds all of the C# libraries from the JSONs.

**Comment by AntoineDao** [comment]
I've added @MingboPeng as I expect we'll be doing a bit of back and forth.

**Comment by AntoineDao** [comment]
[Done!](https://github.com/ladybug-tools/dragonfly-schema-dotnet/commit/a63849c3c3195e7f05f5e7cd62c3d4390b7ee084)
